Repository Requisitos-de-Software/2021.2-ENEM, pull requests merged in 2022-04, with the labels that each got.

#84 fixing some inconsistency
  docs/analise/verificacao/elicitacao/tecnicas-elicitacao/brainstorming.md
  docs/analise/verificacao/elicitacao/tecnicas-elicitacao/entrevista.md
  docs/analise/verificacao/elicitacao/tecnicas-elicitacao/introspeccao.md
  docs/analise/verificacao/elicitacao/tecnicas-elicitacao/observacao.md
  docs/analise/verificacao/elicitacao/tecnicas-elicitacao/questionario.md
  docs/analise/verificacao/elicitacao/tecnicas-elicitacao/storyboard.md
  docs/apresentacoes/apresentacao1.md
  docs/apresentacoes/apresentacao2.md
  docs/apresentacoes/apresentacao3.md
  docs/apresentacoes/apresentacao4.md
  docs/apresentacoes/apresentacao5.md
  docs/apresentacoes/apresentacao6.md
  docs/elicitacao/tecnicas-elicitacao/entrevista.md
  docs/elicitacao/tecnicas-elicitacao/questionario.md
  docs/modelagem/agil/backlog.md
  docs/modelagem/casos-de-uso.md
  docs/modelagem/img/EnemApp.drawio.png
  docs/modelagem/img/resultado_anteriores.drawio.png
  docs/modelagem/nfrframework.md
  docs/planejamento/cronograma.md
  docs/planejamento/ferramentas.md
  docs/planejamento/img/drawio.png
  docs/pre-rastreabilidade/rich_picture.md
  docs/sprints/sprint1.md
  docs/sprints/sprint2.md
  docs/sprints/sprint3.md
  docs/sprints/sprint4.md
  docs/sprints/sprint5.md
  mkdocs.yml
Labels: documentation, Improving

#93 Adicionando a Priorização
  docs/priorização/priorização.md
  mkdocs.yml
Labels: documentation

#94 Correção do layout priorização
  docs/priorização/priorização.md
  mkdocs.yml
Labels: Improving

#97 Fix/some problems deploy
  .gitignore
  docs/modelagem/especificacao-suplementar.md
  docs/modelagem/nfrframework.md
  docs/pos-rastreabilidade/backward-from.md
Labels: Improving
